font_family JetBrainsMono Nerd Font
font_size 12
bold_font auto
italic_font auto
bold_italic_font auto

cursor_shape underline
cursor_blink_interval 0
shell_integration enabled no-cursor

window_padding_width 0
confirm_os_window_close 0
scrollback_lines 10000
background_opacity 0.9

sync_to_monitor yes
repaint_delay 1
input_delay 1
